### ISSUE TITLE
Organization Dashboard

### ISSUE THREAD

**Issue by reneepinna** [Refugee-Aid-Capstone/refugee-aid-fe#22]

**Comment by Sulton88Mehron90** [comment]
# Develop Organization Dashboard

## Description

We need to develop an Organization Dashboard for our application. This dashboard is essential for organizations to view and manage aid requests. The dashboard should also provide a warm welcome message to the logged-in organization and allow them to view details of each aid request.

## Requirements:

1. **Navigation Bar Integration**: The dashboard should integrate with our existing `NavBar` component.
2. **Authentication Check**: Only logged-in organizations should be able to view the dashboard.
3. **Loading State**: Display the spinner when the data is being fetched.
4. **Error Handling**: Proper error messages should be displayed if there's an issue fetching data.
5. **Display Organization Data**: Once the data is fetched, display the organization's details and aid requests.
6. **Aid Requests List**: The aid requests should be listed with details like description and status. Future improvements should allow actions like approve/decline.
7. **Styling**: The dashboard should incorporate our brand colors:
   - Blue (#2196F3) for trust and confidence
   - White (#FFFFFF) for purity and new beginnings
   - Green (#0ECB3A) for hope and growth

## Technical Details:

The query to fetch organization data is already available as `GET_ONE_ORG`. It currently uses a placeholder `'your-organization-id'`. This needs to be replaced with the actual ID once user authentication and organization registration is set up.
